<?php

include_once('ca_resource_library.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_resource_library_perm() {
  return array('ca_resource library change templates'); 
}

/**
 * Implementation of hook_menu().
 */
function ca_resource_library_menu() {
  $items['admin/settings/ca_resource_library'] = array(
    'title' => 'CA Resource Library: Admin',
    'description' => 'Change the look and feel of the ca_resource library module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_resource_library_admin_settings_form'),
    'access arguments' => array('ca_resource library change templates'),
    'file' => 'ca_resource_library.admin.inc',
    'file path' => drupal_get_path('module', 'ca_resource_library') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function ca_resource_library_action_info() {
  return array(
    'ca_resource_library_add_resource_library_admin_action' => array(
      'type' => 'user',
      'description' => t('Add resource library administrator role'),
    ),
    'ca_resource_library_remove_resource_library_admin_action' => array(
      'type' => 'user',
      'description' => t('Remove resource library administrator role'),
    ),
    'ca_resource_library_add_resource_library_writer_action' => array(
      'type' => 'user',
      'description' => t('Add resource library writer role'),
    ),
    'ca_resource_library_remove_resource_library_writer_action' => array(
      'type' => 'user',
      'description' => t('Remove resource library writer role'),
    ),
  );
}

function ca_resource_library_add_resource_library_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'resource library administrator') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_resource_library_add_resource_library_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Resource Library Administrator',
  );
  return $form;
}

function ca_resource_library_add_resource_library_admin_action_submit(&$form, &$form_state) {
  
}

function ca_resource_library_remove_resource_library_admin_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'resource library administrator') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_resource_library_remove_resource_library_admin_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Resource Library Administrator',
  );
  return $form;
}

function ca_resource_library_remove_resource_library_admin_action_submit(&$form, &$form_state) {
  
}

function ca_resource_library_add_resource_library_writer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'resource library writer') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_resource_library_add_resource_library_writer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to Resource Library Writer',
  );
  return $form;
}

function ca_resource_library_add_resource_library_writer_action_submit(&$form, &$form_state) {
  
}

function ca_resource_library_remove_resource_library_writer_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'resource library writer') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_resource_library_remove_resource_library_writer_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from Resource Library Writer',
  );
  return $form;
}

function ca_resource_library_remove_resource_library_writer_action_submit(&$form, &$form_state) {
  
}  

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_resource_library_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_resource_library_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_resource_library' || $subtask['name'] == 'home' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_resource_library') . "/css/ca_resource_library.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_resource_library_views_pre_render(&$view) {
  if ($view->name == 'resource_library') {
    drupal_add_css(drupal_get_path('module', 'ca_resource_library') . "/css/ca_resource_library.css", 'module', 'all', FALSE);
  }
}

